# -*- mode: python -*-

load("@drake//tools/skylark:pathutils.bzl", "join_paths")

def _impl(repository_ctx):
    if "IPOPT_PATH" not in repository_ctx.os.environ:
        fail("IPOPT_PATH environment variable was NOT set")

    ipopt_lib_path = join_paths(repository_ctx.os.environ["IPOPT_PATH"], "lib")

    file_content = """# -*- python -*-

# DO NOT EDIT: generated by sipopt_repository()

licenses(["reciprocal"])  # EPL-1.0

cc_library(
    name = "sipopt",
    linkopts = [
        "-lsipopt",
        "-L{0}",
        "-Wl,-rpath,{0}",
    ],
    visibility = ["//visibility:public"],
    deps = ["@ipopt"],
)
""".format(ipopt_lib_path)

    repository_ctx.file(
        "BUILD.bazel",
        content = file_content,
        executable = False,
    )

sipopt_repository = repository_rule(
    environ = ["IPOPT_PATH"],
    local = True,
    implementation = _impl,
)
