#!/bin/bash

# This shell script and the accompanying Dockerfile and shell scripts are used
# by the project maintainers to create the precompiled vtk binaries that are
# downloaded during the build. They are neither called during the build nor
# expected to be called by most developers or users of the project.

set -euxo pipefail

rm -f \
  vtk-*-bionic-x86_64.tar.gz \
  vtk-bionic-x86_64.tar.gz.sha256 \
  vtk-*-focal-x86_64.tar.gz \
  vtk-focal-x86_64.tar.gz.sha256

docker rmi -f vtk-bionic-build vtk-focal-build 2> /dev/null

docker build \
  --build-arg CODENAME=bionic \
  -f "${BASH_SOURCE%/*}/Dockerfile" \
  -t vtk-bionic \
  "${BASH_SOURCE%/*}"
docker run --name vtk-bionic-build -dt vtk-bionic
trap 'docker rm -f vtk-bionic-build' EXIT
docker cp vtk-bionic-build:"$(docker exec vtk-bionic-build find /opt/vtk/ -maxdepth 1 -name 'vtk-*-bionic-x86_64.tar.gz')" .

shasum -a 256 vtk-*-bionic-x86_64.tar.gz | tee vtk-bionic-x86_64.tar.gz.sha256

docker build \
  --build-arg CODENAME=focal \
  -f "${BASH_SOURCE%/*}/Dockerfile" \
  -t vtk-focal \
  "${BASH_SOURCE%/*}"
docker run --name vtk-focal-build -dt vtk-focal
trap 'docker rm -f vtk-bionic-build vtk-focal-build' EXIT
docker cp vtk-focal-build:"$(docker exec vtk-focal-build find /opt/vtk/ -maxdepth 1 -name 'vtk-*-focal-x86_64.tar.gz')" .

shasum -a 256 vtk-*-focal-x86_64.tar.gz | tee vtk-focal-x86_64.tar.gz.sha256
