#!/bin/bash

# This shell script and the accompanying Dockerfile and shell scripts are used
# by the project maintainers to create the precompiled vtk binaries that are
# downloaded during the build. They are neither called during the build nor
# expected to be called by most developers or users of the project.

set -euxo pipefail

if [[ ! -x /.dockerenv ]]; then
  echo 'ERROR: This script should be run via the accompanying Dockerfile' >&2
  exit 1
fi

export DEBIAN_FRONTEND=noninteractive

apt-get update -qq
apt-get install --no-install-recommends -o Dpkg::Use-Pty=0 -qy \
    binutils \
    ca-certificates \
    cmake \
    g++ \
    gcc \
    libdouble-conversion-dev \
    libeigen3-dev \
    libexpat1-dev \
    libglew-dev \
    libglib2.0-dev \
    libglvnd-dev \
    libjpeg-turbo8-dev \
    libjsoncpp-dev \
    liblz4-dev \
    liblzma-dev \
    libpng-dev \
    libqt5x11extras5-dev \
    libtbb-dev \
    libxt-dev \
    lsb-release \
    ninja-build \
    patch \
    python3-dev \
    python3-numpy \
    qt5-default \
    qttools5-dev \
    wget \
    zlib1g-dev

if [[ "$(lsb-release -cs)" == 'focal' ]]; then
  apt-get install --no-install-recommends -o Dpkg::Use-Pty=0 -qy \
    libfreetype-dev \
    libtiff-dev
else
  apt-get install --no-install-recommends -o Dpkg::Use-Pty=0 -qy \
    libfreetype6-dev \
    libtiff5-dev
fi

set +x
rm -rf /var/lib/apt/lists/*
set -x

wget -nv https://gitlab.kitware.com/vtk/vtk/-/archive/v8.2.0/vtk-v8.2.0.tar.gz
echo 'a42a9586f729273912a1230969fa3f8058b6d6f865485ca23893da97106516ef  vtk-v8.2.0.tar.gz' \
  | sha256sum -c
tar --one-top-level=vtk-src --strip-components=1 -xzf vtk-v*.tar.gz
rm -f vtk-v*.tar.gz

pushd vtk-src
patch -p1 -i ../vtk_image_io.patch
patch -p1 -i ../vtk_rendering_ospray.patch
patch -p1 -i ../vtk_wrap_python.patch
patch -p1 -i ../vtk_wrapping_tools.patch
popd
rm -f vtk_*.patch

mkdir -p vtk-bin /opt/vtk
pushd vtk-bin
cmake \
  -DBUILD_TESTING:BOOL=OFF \
  -DCMAKE_BUILD_TYPE:STRING=Release \
  -DCMAKE_C_FLAGS:STRING='-D_FORTIFY_SOURCE=2 -fstack-protector-strong' \
  -DCMAKE_CXX_FLAGS:STRING='-D_FORTIFY_SOURCE=2 -fstack-protector-strong' \
  -DCMAKE_EXE_LINKER_FLAGS:STRING='-Wl,-Bsymbolic-functions -Wl,-z,now -Wl,-z,relro' \
  -DCMAKE_INSTALL_PREFIX:STRING=/opt/vtk \
  -DCMAKE_MODULE_LINKER_FLAGS:STRING='-Wl,-Bsymbolic-functions -Wl,-z,now -Wl,-z,relro' \
  -DCMAKE_SHARED_LINKER_FLAGS:STRING='-Wl,-Bsymbolic-functions -Wl,-z,now -Wl,-z,relro' \
  -DCMAKE_SHARED_MODULE_SUFFIX:STRING="$(python3-config --extension-suffix)" \
  -DModule_vtkCommonCore:BOOL=ON \
  -DModule_vtkCommonDataModel:BOOL=ON \
  -DModule_vtkCommonExecutionModel:BOOL=ON \
  -DModule_vtkCommonMath:BOOL=ON \
  -DModule_vtkCommonSystem:BOOL=ON \
  -DModule_vtkCommonTransforms:BOOL=ON \
  -DModule_vtkFiltersCore:BOOL=ON \
  -DModule_vtkFiltersExtraction:BOOL=ON \
  -DModule_vtkFiltersGeneral:BOOL=ON \
  -DModule_vtkFiltersGeometry:BOOL=ON \
  -DModule_vtkFiltersPython:BOOL=ON \
  -DModule_vtkFiltersSources:BOOL=ON \
  -DModule_vtkFiltersTexture:BOOL=ON \
  -DModule_vtkGUISupportQt:BOOL=ON \
  -DModule_vtkImagingCore:BOOL=ON \
  -DModule_vtkInteractionStyle:BOOL=ON \
  -DModule_vtkInteractionWidgets:BOOL=ON \
  -DModule_vtkIOGeometry:BOOL=ON \
  -DModule_vtkIOImage:BOOL=ON \
  -DModule_vtkIOImport:BOOL=ON \
  -DModule_vtkIOLegacy:BOOL=ON \
  -DModule_vtkIOPLY:BOOL=ON \
  -DModule_vtkIOXML:BOOL=ON \
  -DModule_vtkRenderingAnnotation:BOOL=ON \
  -DModule_vtkRenderingCore:BOOL=ON \
  -DModule_vtkRenderingOpenGL2:BOOL=ON \
  -DModule_vtkRenderingOSPRay:BOOL=ON \
  -DOSPRAY_INSTALL_DIR:PATH=/opt/vtk \
  -DVTK_ENABLE_VTKPYTHON:BOOL=OFF \
  -DVTK_Group_Imaging:BOOL=OFF \
  -DVTK_Group_MPI:BOOL=OFF \
  -DVTK_Group_Qt:BOOL=OFF \
  -DVTK_Group_Rendering:BOOL=OFF \
  -DVTK_Group_StandAlone:BOOL=OFF \
  -DVTK_Group_Tk:BOOL=OFF \
  -DVTK_Group_Views:BOOL=OFF \
  -DVTK_Group_Web:BOOL=OFF \
  -DVTK_LEGACY_REMOVE:BOOL=ON \
  -DVTK_PYTHON_VERSION:STRING=3 \
  -DVTK_QT_VERSION:STRING=5 \
  -DVTK_RENDERING_BACKEND=OpenGL2 \
  -DVTK_USE_SYSTEM_DOUBLECONVERSION=ON \
  -DVTK_USE_SYSTEM_EIGEN:BOOL=ON \
  -DVTK_USE_SYSTEM_EXPAT:BOOL=ON \
  -DVTK_USE_SYSTEM_FREETYPE:BOOL=ON \
  -DVTK_USE_SYSTEM_GLEW:BOOL=ON \
  -DVTK_USE_SYSTEM_JPEG:BOOL=ON \
  -DVTK_USE_SYSTEM_JSONCPP:BOOL=ON \
  -DVTK_USE_SYSTEM_LZ4:BOOL=ON \
  -DVTK_USE_SYSTEM_LZMA:BOOL=ON \
  -DVTK_USE_SYSTEM_PNG:BOOL=ON \
  -DVTK_USE_SYSTEM_TIFF:BOOL=ON \
  -DVTK_USE_SYSTEM_ZLIB:BOOL=ON \
  -DVTK_WRAP_PYTHON:BOOL=ON \
  -GNinja \
  -Wno-dev \
  ../vtk-src
ninja install/strip
popd
rm -rf vtk-*

find /opt/vtk -name __pycache__ -type d -exec rm -rf {} +
rm -f /opt/vtk/plugins

# shellcheck disable=SC2016
sed -i 's|VTK_RUNTIME_DIRS "/opt/vtk/bin"|VTK_RUNTIME_DIRS "${VTK_INSTALL_PREFIX}/bin"|g; s|VTK_RUNTIME_DIRS "/opt/vtk/lib"|VTK_RUNTIME_DIRS "${VTK_INSTALL_PREFIX}/lib"|g' \
  /opt/vtk/lib/cmake/vtk-*/VTKConfig.cmake
# shellcheck disable=SC2016
sed -i 's|/opt/vtk|${_IMPORT_PREFIX}|g' \
  /opt/vtk/lib/cmake/vtk-*/VTKTargets.cmake
# shellcheck disable=SC2016
sed -i 's|VTK_PYTHONPATH "/opt/vtk/lib/python3.\([0-9]\)/site-packages"|VTK_PYTHONPATH "${VTK_INSTALL_PREFIX}/lib/python3.\1/site-packages"|g' \
  /opt/vtk/lib/cmake/vtk-*/Modules/vtkPython.cmake
