#!/bin/bash

# This shell script and the accompanying Dockerfile and shell scripts are used
# by the project maintainers to create the precompiled drake-visualizer binaries
# that are downloaded during the build. They are neither called during the build
# nor expected to be called by most developers or users of the project.

set -euxo pipefail

rm -f \
  dv-*-bionic-x86_64.tar.gz \
  dv-*-bionic-x86_64.tar.gz.sha256 \
  dv-*-focal-x86_64.tar.gz \
  dv-*-focal-x86_64.tar.gz.sha256

docker rmi -f dv-bionic-build dv-focal-build 2> /dev/null

docker build \
  --build-arg CODENAME=bionic \
  -f "${BASH_SOURCE%/*}/Dockerfile" \
  -t dv-bionic \
  "${BASH_SOURCE%/*}"
docker run --name dv-bionic-build -dt dv-bionic
trap 'docker rm -f dv-bionic-build' EXIT
docker cp dv-bionic-build:"$(docker exec dv-bionic-build find /opt/director/ -maxdepth 1 -name 'dv-*-bionic-x86_64.tar.gz')" .

shasum -a 256 dv-*-bionic-x86_64.tar.gz | tee dv-bionic-x86_64.tar.gz.sha256

docker build \
  --build-arg CODENAME=focal \
  -f "${BASH_SOURCE%/*}/Dockerfile" \
  -t dv-focal \
  "${BASH_SOURCE%/*}"
docker run --name dv-focal-build -dt dv-focal
trap 'docker rm -f dv-bionic-build dv-focal-build' EXIT
docker cp dv-focal-build:"$(docker exec dv-focal-build find /opt/director/ -maxdepth 1 -name 'dv-*-focal-x86_64.tar.gz')" .

shasum -a 256 dv-*-focal-x86_64.tar.gz | tee dv-focal-x86_64.tar.gz.sha256
